# Theta configuration
genesis:
  hash: "0x9cf90c90d02c1c6a45afe2990f1426e4c7f936630f2ce2882b46fe33f5f58144"
p2p:
  port: 12100
  seeds: 10.10.1.25:12100,10.10.1.26:12100,10.10.1.27:12100,10.10.1.28:12100
  seedPeerOnlyOutbound: true
rpc:
   enabled: true
log:
  levels: "*:info"
consensus:
  minBlockInterval: 1
subchain:
  mainchainEthRpcURL: "http://10.10.1.2:18888/rpc"
  subchainEthRpcURL: "http://127.0.0.1:19888/rpc"
  chainRegistrarOnMainchain: "0x08425D9Df219f93d5763c3e85204cb5B4cE33aAa"
  mainchainTFuelTB: "0x7f1C87Bd3a22159b8a2E5D195B1a3283D10ea895"
  mainchainTNT20TB: "0x2Ce636d6240f8955d085a896e12429f8B3c7db26"
  mainchainTNT721TB: "0xEd8d61f42dC1E56aE992D333A4992C3796b22A74"
  mockTNT20: "0x47c5e40890bcE4a473A49D7501808b9633F29782"
  updateInterval: 200
  chainID: 360006
