# Theta configuration
genesis:
  hash: "0xf14161e36b58ec588b12ef5591ff7754c9eaf5de3455e5c1f09f4c2cc09f75cf"
p2p:
  port: 12100
  seeds: 10.10.1.33:12100,10.10.1.34:12100,10.10.1.35:12100,10.10.1.36:12100
  seedPeerOnlyOutbound: true
rpc:
  enabled: true
log:
  levels: "*:info"
consensus:
  minBlockInterval: 1
subchain:
  mainchainEthRpcURL: "http://10.10.1.2:18888/rpc"
  subchainEthRpcURL: "http://127.0.0.1:19888/rpc"
  chainRegistrarOnMainchain: "0x08425D9Df219f93d5763c3e85204cb5B4cE33aAa"
  mainchainTFuelTB: "0x7f1C87Bd3a22159b8a2E5D195B1a3283D10ea895"
  mainchainTNT20TB: "0x2Ce636d6240f8955d085a896e12429f8B3c7db26"
  mainchainTNT721TB: "0xEd8d61f42dC1E56aE992D333A4992C3796b22A74"
  mockTNT20: "0x47c5e40890bcE4a473A49D7501808b9633F29782"
  updateInterval: 200
  chainID: 360008
